language: node_js
node_js:
  - "node"

install:
  - npm run install_deploy
  - npm install -g gulp
  - npm install gulp-shell
  - npm install gulp-typescript  
  - npm install gulp-uglify
  - npm install -g typings

script:
  - gulp --gulpfile ./static/gulp_deploy.js
  - ./node_modules/.bin/karma start ./test/karma.conf.js --single-run --browsers PhantomJS


