language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - npm install
  - npm install -g gulp-cli

script:
  - gulp --gulpfile ./gulp_deploy.js
  - ./node_modules/.bin/karma start ./test/karma.conf.js --single-run --browsers PhantomJS

after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}