language: python
python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - npm install
  - npm install -g gulp-cli

script:
  - gulp --gulpfile ./gulp_deploy.js
  - ./node_modules/.bin/karma start ./test/karma.conf.js --single-run --browsers PhantomJS

before_deploy:
  - gulp --gulpfile ./gulp_deploy.js post_deploy_clean_up

deploy:
  provider: heroku
  api_key:
    secure: cdOQwVKRsuuuFkD9g3IWmupjX6JIOyK0mapVU99xTBQIrDJAsBfAm6QPGep6DWBzl6DAttlzyUOpAxCJUy08bMsUIsQq2vQAhhuBQOTm2Wq/rhg0WlqrsoT/pSTrxH0iDxQ8x9lm0+qpdG4qI+KOE1F+bchu8yPsCp/UgZY1aWuq5Ao2OiZpnCIztD3AwslB/TpAPax3uIYXCjD7sqUmu6YizWeoJyjumHRTJ+hWNQuKS3ODnhHc4vAQP8FhQ/ZQDkApF90f8SmnHzYzvYNAoeZ5cVN0cJThxSk0tCwFMeEtiOvPo4MV1YtNEQhUcfyUFfR28ld79+PRDlF/XkBQm6XhniBvOwNmSsUPNiDQVOTEO/0PaGYrX5Ldc7UBx419CznDF4KvnUSz1AZFMUVQley8RqFFARSI5HnnHqpe0mSqCItx/UspnZJiGY/uPxK12OlG+xCj5hAq0QemSoRItfiNxHj4LvI12LAnTtv0TwOKdiCy5y0MTs3ffUZsakgIz1xKrgfv68nm0uy5TrUmuwVA21MMiqZ2oSK+EKOulfJ3CkVUtadMW+0hV4tPVGD3Q4gGflVmFU7Aa/wPW4iochx9XwxRWsFLrprLHuZLgSQCtox4pSfWbSfLNje3GRHRJ18725PHzhA3xFShMUw3lXg7wdaqh4+idjVD6KevpuA=
  skip_cleanup: true    
  app: ndc-ng2
  buildpack: ruby

